SSS bye getActiveRecords TTT XXX
- note these are the few uses that do not use fid/eid

XXX due to TODO comment and also

patcher_dialog.py  272 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 190, in PatchExecute
    self._save_pbash(patchFile, patch_name)
  File "bash\basher\patcher_dialog.py", line 280, in _save_pbash
    patchFile.safeSave()
  File "bash\mod_files.py", line 293, in safeSave
    self.save(filePath.temp)
  File "bash\mod_files.py", line 325, in save
    selfTops[rsig].dump(out)
  File "bash\brec\record_groups.py", line 666, in dump
    dialogue.dump(out)
  File "bash\brec\record_groups.py", line 458, in dump
    self._sort_group()
  File "bash\brec\record_groups.py", line 548, in _sort_group
    if not r.prev_info:
AttributeError: 'MreDial' object has no attribute 'prev_info'

Traceback (most recent call last):
  File "bash\gui\events.py", line 177, in _post
    result = listener(*listener_args)
  File "bash\balt.py", line 825, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\patcher_dialog.py", line 190, in PatchExecute
    self._save_pbash(patchFile, patch_name)
  File "bash\basher\patcher_dialog.py", line 280, in _save_pbash
    patchFile.safeSave()
  File "bash\mod_files.py", line 293, in safeSave
    self.save(filePath.temp)
  File "bash\mod_files.py", line 325, in save
    selfTops[rsig].dump(out)
  File "bash\brec\record_groups.py", line 666, in dump
    dialogue.dump(out)
  File "bash\brec\record_groups.py", line 458, in dump
    self._sort_group()
  File "bash\brec\record_groups.py", line 548, in _sort_group
    if not r.prev_info:
AttributeError: 'MreDial' object has no attribute 'prev_info'