Monkey patch getlocale
Run python -m pytest
  python -m pytest
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.9.9\x64
============================= test session starts =============================
platform win32 -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: D:\a\wrye-bash\wrye-bash
collected 122 items

Mopy\bash\tests\test_bolt.py ........................................... [ 35%]
.                                                                        [ 36%]
Mopy\bash\tests\test_localize.py FF                                      [ 37%]
Mopy\bash\tests\test_bosh\test_cosaves.py .............................. [ 62%]
..                                                                       [ 63%]
Mopy\bash\tests\test_bosh\test_list_info.py .                            [ 64%]
Mopy\bash\tests\test_bosh\test_loot_parser.py .......................... [ 86%]
.................                                                        [100%]

================================== FAILURES ===================================
____________________________ test_setlocale_pl_PL _____________________________

capsys = <_pytest.capture.CaptureFixture object at 0x0000024A980AADC0>

    def test_setlocale_pl_PL(capsys):
        """Test setting locale to default."""
        with capsys.disabled():
>           setup_locale('pl_PL', __wx)

Mopy\bash\tests\test_localize.py:35:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Mopy\bash\localize.py:126: in setup_locale
    f"{locale.getlocale()}'")
C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\locale.py:593: in getlocale
    return _parse_localename(localename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

localename = 'pl-PL'

    def _parse_localename(localename):

        """ Parses the locale code for localename and returns the
            result as tuple (language code, encoding).

            The localename is normalized and passed through the locale
            alias engine. A ValueError is raised in case the locale name
            cannot be parsed.

            The language code corresponds to RFC 1766.  code and encoding
            can be None in case the values cannot be determined or are
            unknown to this implementation.

        """
        code = normalize(localename)
        if '@' in code:
            # Deal with locale modifiers
            code, modifier = code.split('@', 1)
            if modifier == 'euro' and '.' not in code:
                # Assume Latin-9 for @euro locales. This is bogus,
                # since some systems may use other encodings for these
                # locales. Also, we ignore other modifiers.
                return code, 'iso-8859-15'

        if '.' in code:
            return tuple(code.split('.')[:2])
        elif code == 'C':
            return None, None
        elif code == 'UTF-8':
            # On macOS "LC_CTYPE=UTF-8" is a valid locale setting
            # for getting UTF-8 handling for text.
            return None, 'UTF-8'
>       raise ValueError('unknown locale: %s' % localename)
E       ValueError: unknown locale: pl-PL

C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\locale.py:501: ValueError
____________________________ test_setlocale_nocli _____________________________

capsys = <_pytest.capture.CaptureFixture object at 0x0000024A9835E700>

    def test_setlocale_nocli(capsys):
        """Test setting locale to pl_PL."""
        with capsys.disabled(): # https://stackoverflow.com/a/41533292/281545
>           setup_locale('', __wx)

Mopy\bash\tests\test_localize.py:46:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Mopy\bash\localize.py:126: in setup_locale
    f"{locale.getlocale()}'")
C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\locale.py:593: in getlocale
    return _parse_localename(localename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

localename = 'en-US'

    def _parse_localename(localename):

        """ Parses the locale code for localename and returns the
            result as tuple (language code, encoding).

            The localename is normalized and passed through the locale
            alias engine. A ValueError is raised in case the locale name
            cannot be parsed.

            The language code corresponds to RFC 1766.  code and encoding
            can be None in case the values cannot be determined or are
            unknown to this implementation.

        """
        code = normalize(localename)
        if '@' in code:
            # Deal with locale modifiers
            code, modifier = code.split('@', 1)
            if modifier == 'euro' and '.' not in code:
                # Assume Latin-9 for @euro locales. This is bogus,
                # since some systems may use other encodings for these
                # locales. Also, we ignore other modifiers.
                return code, 'iso-8859-15'

        if '.' in code:
            return tuple(code.split('.')[:2])
        elif code == 'C':
            return None, None
        elif code == 'UTF-8':
            # On macOS "LC_CTYPE=UTF-8" is a valid locale setting
            # for getting UTF-8 handling for text.
            return None, 'UTF-8'
>       raise ValueError('unknown locale: %s' % localename)
E       ValueError: unknown locale: en-US

C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\locale.py:501: ValueError
=========================== short test summary info ===========================
FAILED Mopy/bash/tests/test_localize.py::test_setlocale_pl_PL - ValueError: u...
FAILED Mopy/bash/tests/test_localize.py::test_setlocale_nocli - ValueError: u...
======================== 2 failed, 120 passed in 9.59s ========================