Replacing getActiveRecords with iter_present_records XXXX
- kept rfid_ for unused (oldish code)

Mopy/bash/brec/record_groups.py: some tiny performance for
iter_present_records

XXX BP blows with:

patcher_dialog.py  263 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\patcher_dialog.py", line 182, in PatchExecute
    self._save_pbash(patchFile, patch_name)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\patcher_dialog.py", line 272, in _save_pbash
    patchFile.safeSave()
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 287, in safeSave
    self.save(filePath.temp)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 319, in save
    selfTops[rsig].dump(out)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 671, in dump
    dialogue.dump(out)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 463, in dump
    self._sort_group()
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 553, in _sort_group
    if not r.prev_info:
AttributeError: 'MreDial' object has no attribute 'prev_info'

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\events.py", line 178, in _post
    result = listener(*listener_args)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\balt.py", line 808, in _conversation_wrapper
    return func(*args, **kwargs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\patcher_dialog.py", line 182, in PatchExecute
    self._save_pbash(patchFile, patch_name)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\patcher_dialog.py", line 272, in _save_pbash
    patchFile.safeSave()
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 287, in safeSave
    self.save(filePath.temp)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 319, in save
    selfTops[rsig].dump(out)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 671, in dump
    dialogue.dump(out)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 463, in dump
    self._sort_group()
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 553, in _sort_group
    if not r.prev_info:
AttributeError: 'MreDial' object has no attribute 'prev_info'



r = {MreDial} <HELLO [DIAL:000000D2]>
 _has_duplicate_attrs = {bool} False
 _rec_sig = {bytes: 4} b'DIAL'
 added_quests = {list: 188} [14687, 14688, 14689, 31534, 49209, 49210, 49211, 49212, 49592, 49675, 67074, 83618, 83619, 83620, 83621, 83622, 83623, 83624, 83625, 83626, 83627, 83628, 83629, 83631, 83632, 89531, 91622, 91928, 95750, 96309, 96311, 96312, 96313, 119324, 121762, 124706,
 changed = {bool} False
 data = {bytes: 1911} b'EDID\x06\x00HELLO\x00QSTI\x04\x00_9\x00\x00QSTI\x04\x00`9\x00\x00QSTI\x04\x00a9\x00\x00QSTI\x04\x00.{\x00\x00QSTI\x04\x009\xc0\x00\x00QSTI\x04\x00:\xc0\x00\x00QSTI\x04\x00;\xc0\x00\x00QSTI\x04\x00<\xc0\x00\x00QSTI\x04\x00\xb8\xc1\x00\x00QSTI\x04\x00\x0b\
 dialType = {int} 1
 eid = {str} 'HELLO'
 fid = {int} 210
 flags1 = {__Flags} 0x00000000 (None)
 flags1_ = {type} <class 'bash.bolt.Flags.from_names.<locals>.__Flags'>
 flags2 = {int} 0
 full = {str} 'HELLO'
 header = {RecHeader} <Record Header: [DIAL:000000D2] v0>
 inName = {Path: 29} No More Annoying Comments.esp
 isKeyedByEid = {bool} False
 longFids = {bool} False
 melSet = {MelSet} <bash.brec.record_structs.MelSet object at 0x0000026660353D90>
 rec_sig = {bytes: 4} b'DIAL'
 rec_str = {str} 'DIAL'
 removed_quests = {list: 0} []
 simpleTypes = {set: 53} {b'STAT', b'ANIO', b'AMMO', b'FLOR', b'MGEF', b'DOOR', b'CLAS', b'EYES', b'ALCH', b'GMST', b'BSGN', b'SLGM', b'RACE', b'SCPT', b'LSCR', b'SKIL', b'CREA', b'SOUN', b'EFSH', b'TREE', b'CSTY', b'WEAP', b'SPEL', b'KEYM', b'QUST', b'PACK', b'NPC_', b'LVLI', b'W
 size = {int} 1911
 subrec_sig_to_record_sig = {defaultdict: 169} defaultdict(<class 'set'>, {b'EDID': {b'STAT', b'ANIO', b'PACK', b'AMMO', b'NPC_', b'REFR', b'LVLI', b'WTHR', b'HAIR', b'REGN', b'SBSP', b'FLOR', b'DIAL', b'MGEF', b'ENCH', b'ARMO', b'DOOR', b'WRLD', b'CLMT', b'GRAS', b'APPA', b'BOOK', b'LVSP', b'FURN', b'
 subtype_attr = {dict: 3} {b'EDID': 'eid', b'FULL': 'full', b'MODL': 'model'}
 type_class = {dict: 64} {b'ACHR': <class 'bash.game.oblivion.records.MreAchr'>, b'ACRE': <class 'bash.game.oblivion.records.MreAcre'>, b'ACTI': <class 'bash.game.oblivion.records.MreActi'>, b'ALCH': <class 'bash.game.oblivion.records.MreAlch'>, b'AMMO': <class 'bash.game.oblivion



and another error from the same bugdump

record_structs.py  610 loadData: Error loading ACRE record and/or subrecord: 01003DF9
  eid = None
  subrecord = XLOD
  subrecord size = 12
  file pos = 9858791
NoneType: None

mod_files.py  250 load: Error in GTAesgaard.esp
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 227, in load
    new_top.load_rec_group(ins, load_fully)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 71, in load_rec_group
    self._load_rec_group(ins, ins.tell() + self.header.blob_size())
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1718, in _load_rec_group
    worldBlock = MobWorld(header,selfLoadFactory,world,ins,True)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1379, in __init__
    super(MobWorld, self).__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1114, in __init__
    super(MobCells, self).__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 62, in __init__
    if ins: self.load_rec_group(ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 71, in load_rec_group
    self._load_rec_group(ins, ins.tell() + self.header.blob_size())
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1458, in _load_rec_group
    build_cell_block(unpack_block=unpackCellBlocks,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1404, in build_cell_block
    cellBlock = MobCell(header, selfLoadFactory, cell, ins, True)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 796, in __init__
    super(MobCell, self).__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 62, in __init__
    if ins: self.load_rec_group(ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 71, in load_rec_group
    self._load_rec_group(ins, ins.tell() + self.header.blob_size())
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 832, in _load_rec_group
    record = recClass(header,ins,True)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 577, in __init__
    MreRecord.__init__(self, header, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 379, in __init__
    if ins: self.load(ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 430, in load
    self.loadData(ins,inPos+self.size)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 618, in loadData
    raise exception.ModError(ins.inName, error)
bash.exception.ModError: GTAesgaard.esp: Unexpected subrecord: ACRE.XLOD

record_structs.py  610 loadData: Error loading ACRE record and/or subrecord: 01003DF9
  eid = None
  subrecord = XLOD
  subrecord size = 12
  file pos = 9858791
NoneType: None

mod_files.py  250 load: Error in GTAesgaard - Copy.esp
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 227, in load
    new_top.load_rec_group(ins, load_fully)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 71, in load_rec_group
    self._load_rec_group(ins, ins.tell() + self.header.blob_size())
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1718, in _load_rec_group
    worldBlock = MobWorld(header,selfLoadFactory,world,ins,True)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1379, in __init__
    super(MobWorld, self).__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1114, in __init__
    super(MobCells, self).__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 62, in __init__
    if ins: self.load_rec_group(ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 71, in load_rec_group
    self._load_rec_group(ins, ins.tell() + self.header.blob_size())
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1458, in _load_rec_group
    build_cell_block(unpack_block=unpackCellBlocks,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1404, in build_cell_block
    cellBlock = MobCell(header, selfLoadFactory, cell, ins, True)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 796, in __init__
    super(MobCell, self).__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 62, in __init__
    if ins: self.load_rec_group(ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 71, in load_rec_group
    self._load_rec_group(ins, ins.tell() + self.header.blob_size())
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 832, in _load_rec_group
    record = recClass(header,ins,True)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 577, in __init__
    MreRecord.__init__(self, header, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 379, in __init__
    if ins: self.load(ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 430, in load
    self.loadData(ins,inPos+self.size)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 618, in loadData
    raise exception.ModError(ins.inName, error)
bash.exception.ModError: GTAesgaard - Copy.esp: Unexpected subrecord: ACRE.XLOD