Fixup for yet another type error in patcher: EEE monkey patch
This time round we passed a float when an integer is needed - needs
proper (record) fix! Also those tracebacks need show the code context -
would make debugging much easier

https://discord.com/channels/537706885965676554/537710082755133460/921228298175012874

localize.pyc  115 setup_locale: Set wxPython language to 'en_US'
localize.pyc  117 setup_locale: Set Wrye Bash language to 'en_US'
doc_viewer.pyc   38 <module>: pdfviewer using PyMuPDF (GPL)
bash.pyc  246 dump_environment: Using Wrye Bash Version 310.202111240909 (Standalone)
bash.pyc  246 dump_environment: OS info: Windows-10-10.0.19044-SP0, running on Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
bash.pyc  246 dump_environment: Python version: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
bash.pyc  246 dump_environment: Dependency versions:
bash.pyc  246 dump_environment:  - chardet: 4.0.0
bash.pyc  246 dump_environment:  - PyMuPDF: 1.19.1; bundled MuPDF version: 1.19.0
bash.pyc  246 dump_environment:  - python-lz4: 3.1.3; bundled LZ4 version: 1.9.3
bash.pyc  246 dump_environment:  - PyYAML: 6.0
bash.pyc  246 dump_environment:  - wxPython: 4.1.1 msw (phoenix) wxWidgets 3.1.5
bash.pyc  246 dump_environment: Input encoding: None; output encoding: utf-8
bash.pyc  246 dump_environment: Filesystem encoding: utf-8
bash.pyc  246 dump_environment: Command line: ['T:\\SteamLibrary\\steamapps\\common\\Skyrim\\Mopy\\Wrye Bash.exe', '-d']
bash.pyc  491 _import_bush_and_set_game: Searching for game to manage:
bush.pyc  118 _supportedGames: The following games are supported by this version of Wrye Bash:
bush.pyc  121 _supportedGames:  Enderal, Enderal Special Edition, Fallout 3, Fallout 3 (WS), Fallout
bush.pyc  121 _supportedGames:  4, Fallout 4 (WS), Fallout 4 VR, Fallout New Vegas, Fallout New Vegas
bush.pyc  121 _supportedGames:  (WS), Morrowind, Morrowind (WS), Nehrim, Oblivion, Oblivion (WS),
bush.pyc  121 _supportedGames:  Skyrim, Skyrim Special Edition, Skyrim Special Edition (WS), Skyrim VR
bush.pyc  123 _supportedGames: Wrye Bash looked for games in the following places:
bush.pyc  124 _supportedGames:  1. Windows Registry:
bush.pyc  126 _supportedGames:   The following installed games were found via the registry:
bush.pyc   66 _print_found_games:  - Fallout 3: T:\GOG Games\Fallout 3
bush.pyc   66 _print_found_games:  - Fallout 4: D:\SteamLibrary\steamapps\common\Fallout 4
bush.pyc   66 _print_found_games:  - Fallout New Vegas: T:\SteamLibrary\steamapps\common\fallout new vegas
bush.pyc   66 _print_found_games:  - Oblivion: T:\SteamLibrary\steamapps\common\Oblivion
bush.pyc   66 _print_found_games:  - Skyrim: T:\SteamLibrary\steamapps\common\Skyrim
bush.pyc   66 _print_found_games:  - Skyrim Special Edition: T:\SteamLibrary\steamapps\common\Skyrim Special Edition
bush.pyc  135 _supportedGames:   Make sure to run the launcher of each game you installed through Steam
bush.pyc  135 _supportedGames:   once, otherwise Wrye Bash will not be able to find it.
bush.pyc  136 _supportedGames:  2. Windows Store:
bush.pyc  142 _supportedGames:   No installed games with modding enabled were found via the Windows Store.
bush.pyc  147 _supportedGames:   Make sure to enable mods for each Windows Store game you have
bush.pyc  147 _supportedGames:   installed, otherwise Wrye Bash will not be able to find it.
bush.pyc  209 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.pyc  215 _detectGames: Set game mode to Skyrim found in parent directory of Mopy:  T:\SteamLibrary\steamapps\common\Skyrim
bush.pyc  231 __setGame: Using Skyrim game: T:\SteamLibrary\steamapps\common\Skyrim
initialization.pyc  158 init_dirs: My Games location set to C:\Users\Stephanie\OneDrive\Documents\My Games\Skyrim
initialization.pyc  171 init_dirs: LocalAppData location set to C:\Users\Stephanie\AppData\Local\Skyrim
initialization.pyc  219 init_dirs: Game Mods location set to T:\SteamLibrary\steamapps\common\Skyrim Mods
initialization.pyc  224 init_dirs: Bash Mod Data location set to T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Mod Data
initialization.pyc  228 init_dirs: Installers location set to T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Installers
initialization.pyc  230 init_dirs: Installers bash data location set to T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Installers\Bash
initialization.pyc  238 init_dirs: Checking if WB directories exist and creating them if needed:
initialization.pyc  242 init_dirs:  - T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Mod Data
initialization.pyc  242 init_dirs:  - T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Installers
initialization.pyc  242 init_dirs:  - T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Installers\Bain Converters
initialization.pyc  242 init_dirs:  - T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Installers\Bain Converters\--Duplicates
initialization.pyc  242 init_dirs:  - T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Installers\Bain Converters\--Corrupt
initialization.pyc  242 init_dirs:  - T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Installers\Bash
initialization.pyc  242 init_dirs:  - T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Installers\Bash\BSA Cache
loot_parser.pyc   48 <module>: Using LibYAML-based parser
loot_parser.pyc   83 __init__: Using these LOOT paths:
loot_parser.pyc   84 __init__:  Masterlist: C:\Users\Stephanie\AppData\Local\LOOT\Skyrim\masterlist.yaml
loot_parser.pyc   85 __init__:  Userlist: C:\Users\Stephanie\AppData\Local\LOOT\Skyrim\userlist.yaml
loot_parser.pyc   86 __init__:  Taglist (fallback): T:\SteamLibrary\steamapps\common\Skyrim\Mopy\taglists\Skyrim\taglist.yaml
__init__.pyc 3608 initBosh: Initialized loot_parser, compatible with libloot v0.16.x
__init__.pyc 3611 initBosh: Looking for main game INI at C:\Users\Stephanie\OneDrive\Documents\My Games\Skyrim\Skyrim.ini
windows.pyc  967 testUAC: Testing if game folder is UAC-protected
__init__.pyc 1529 _initDB: Initializing BSAInfos
__init__.pyc 1530 _initDB:  store_dir: T:\SteamLibrary\steamapps\common\Skyrim\Data
__init__.pyc 1531 _initDB:  bash_dir: T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Mod Data\BSA Data
__init__.pyc 1529 _initDB: Initializing ModInfos
__init__.pyc 1530 _initDB:  store_dir: T:\SteamLibrary\steamapps\common\Skyrim\Data
__init__.pyc 1531 _initDB:  bash_dir: T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Mod Data
_games_lo.pyc  663 print_lo_paths: Using the following load order files:
_games_lo.pyc  668 print_lo_paths:  - Load order: C:\Users\Stephanie\AppData\Local\Skyrim\loadorder.txt
_games_lo.pyc  670 print_lo_paths:  - Active plugins: C:\Users\Stephanie\AppData\Local\Skyrim\plugins.txt
__init__.pyc 1529 _initDB: Initializing SaveInfos
__init__.pyc 1530 _initDB:  store_dir: C:\Users\Stephanie\OneDrive\Documents\My Games\Skyrim\Saves
__init__.pyc 1531 _initDB:  bash_dir: C:\Users\Stephanie\OneDrive\Documents\My Games\Skyrim\Saves\Bash
__init__.pyc 1529 _initDB: Initializing INIInfos
__init__.pyc 1530 _initDB:  store_dir: T:\SteamLibrary\steamapps\common\Skyrim\Data\INI Tweaks
__init__.pyc 1531 _initDB:  bash_dir: T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Mod Data\INI Data
__init__.pyc 3606 __init__: Constructing panel 'Installers'
__init__.pyc 3616 __init__: Panel 'Installers' constructed successfully
__init__.pyc 3606 __init__: Constructing panel 'Mods'
__init__.pyc 3616 __init__: Panel 'Mods' constructed successfully
__init__.pyc 3606 __init__: Constructing panel 'Saves'
__init__.pyc 3616 __init__: Panel 'Saves' constructed successfully
__init__.pyc 3606 __init__: Constructing panel 'INI Edits'
__init__.pyc 3616 __init__: Panel 'INI Edits' constructed successfully
__init__.pyc 3606 __init__: Constructing panel 'Screenshots'
__init__.pyc 1529 _initDB: Initializing ScreenInfos
__init__.pyc 1530 _initDB:  store_dir: T:\SteamLibrary\steamapps\common\Skyrim
__init__.pyc 1531 _initDB:  bash_dir: T:\SteamLibrary\steamapps\common\Skyrim Mods\Bash Mod Data\Screenshot Data
__init__.pyc 3616 __init__: Panel 'Screenshots' constructed successfully
mod_files.pyc  241 load: Skyrim.esm: Duplicate top-level b'HAZD' group, merging
mod_files.pyc  241 load: Skyrim.esm: Duplicate top-level b'HAZD' group, merging
mod_files.pyc  241 load: Skyrim.esm: Duplicate top-level b'HAZD' group, merging
mod_files.pyc  241 load: Skyrim.esm: Duplicate top-level b'HAZD' group, merging
record_structs.pyc  198 dumpData: Error dumping data:
Traceback (most recent call last):
  File "bash\brec\record_structs.py", line 196, in dumpData
  File "bash\brec\advanced_elements.py", line 893, in dumpData
  File "bash\brec\basic_elements.py", line 183, in dumpData
  File "bash\brec\basic_elements.py", line 233, in pack_subrecord_data
struct.error: required argument is not an integer

record_structs.pyc  199 dumpData: Occurred while dumping <iMaxAttachedArrows [GMST:2E000800]>
record_structs.pyc  209 dumpData: > value: 5.0
record_structs.pyc  209 dumpData: > eid: 'iMaxAttachedArrows'
patcher_dialog.pyc  267 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 186, in PatchExecute
  File "bash\basher\patcher_dialog.py", line 276, in _save_pbash
  File "bash\mod_files.py", line 287, in safeSave
  File "bash\mod_files.py", line 319, in save
  File "bash\brec\record_groups.py", line 266, in dump
  File "bash\brec\record_groups.py", line 255, in getSize
  File "bash\brec\record_groups.py", line 256, in <genexpr>
  File "bash\brec\record_structs.py", line 489, in getSize
  File "bash\brec\record_structs.py", line 627, in dumpData
  File "bash\brec\record_structs.py", line 196, in dumpData
  File "bash\brec\advanced_elements.py", line 893, in dumpData
  File "bash\brec\basic_elements.py", line 183, in dumpData
  File "bash\brec\basic_elements.py", line 233, in pack_subrecord_data
struct.error: required argument is not an integer

Traceback (most recent call last):
  File "bash\gui\events.py", line 178, in _post
  File "bash\balt.py", line 809, in _conversation_wrapper
  File "bash\basher\patcher_dialog.py", line 186, in PatchExecute
  File "bash\basher\patcher_dialog.py", line 276, in _save_pbash
  File "bash\mod_files.py", line 287, in safeSave
  File "bash\mod_files.py", line 319, in save
  File "bash\brec\record_groups.py", line 266, in dump
  File "bash\brec\record_groups.py", line 255, in getSize
  File "bash\brec\record_groups.py", line 256, in <genexpr>
  File "bash\brec\record_structs.py", line 489, in getSize
  File "bash\brec\record_structs.py", line 627, in dumpData
  File "bash\brec\record_structs.py", line 196, in dumpData
  File "bash\brec\advanced_elements.py", line 893, in dumpData
  File "bash\brec\basic_elements.py", line 183, in dumpData
  File "bash\brec\basic_elements.py", line 233, in pack_subrecord_data
struct.error: required argument is not an integer

Mopy/bash/patcher/patchers/preservers.py: values is used all over in records
code