bye utf FFF
  python -m pytest
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.9.9\x64
============================= test session starts =============================
platform win32 -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: D:\a\wrye-bash\wrye-bash
collected 123 items

Mopy\bash\tests\test_bolt.py ........................................... [ 34%]
.                                                                        [ 35%]
Mopy\bash\tests\test_localize.py localize.py   76 setup_locale: cli_target=<wx._core.LanguageInfo object at 0x000001BB4F28FA60>
localize.py  127 setup_locale: Wrye Bash does not support the language family 'pl', will however try to set locale to 'pl_PL'
localize.py  136 setup_locale: target_name='pl_PL'
Flocalize.py   76 setup_locale: cli_target=''
localize.py   83 setup_locale: cli_lang='' - cli_target='' - falling back to (en_US, cp1252) from getdefaultlocale
localize.py   87 setup_locale: wx gave back en_US
localize.py  136 setup_locale: target_name='en_US'
Flocalize.py   76 setup_locale: cli_target=None
localize.py   83 setup_locale: cli_lang='pl-PL' - cli_target=None - falling back to (en_US, cp1252) from getdefaultlocale
localize.py   87 setup_locale: wx gave back en_US
localize.py  136 setup_locale: target_name='en_US'
F                                     [ 38%]
Mopy\bash\tests\test_bosh\test_cosaves.py .............................. [ 62%]
..                                                                       [ 64%]
Mopy\bash\tests\test_bosh\test_list_info.py .                            [ 65%]
Mopy\bash\tests\test_bosh\test_loot_parser.py .......................... [ 86%]
.................                                                        [100%]

================================== FAILURES ===================================
______________________ TestLocalize.test_setlocale_pl_PL ______________________

self = <bash.tests.test_localize.TestLocalize object at 0x000001BB4F5512B0>
capsys = <_pytest.capture.CaptureFixture object at 0x000001BB4F551340>

    def test_setlocale_pl_PL(self, capsys):
        """Test setting locale to default."""
>       self._test_locale("pl_PL", capsys)

Mopy\bash\tests\test_localize.py:59:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Mopy\bash\tests\test_localize.py:48: in _test_locale
    setup_locale(loc, _wx)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cli_lang = 'pl_PL'
_wx = <module 'wx' from 'C:\\hostedtoolcache\\windows\\Python\\3.9.9\\x64\\lib\\site-packages\\wx\\__init__.py'>

...
        bolt.deprint(f'{target_name=}')
        if '.' in target_name:
            target_name = target_name.split('.', 1)[0]
        target_name += '.UTF-8'
        lang_info = _wx.Locale.FindLanguageInfo(target_name)
>       target_language = lang_info.Language
E       AttributeError: 'NoneType' object has no attribute 'Language'

Mopy\bash\localize.py:141: AttributeError