Inline compressCommand: RRR TTT EEE add to default ini
The compressCommand/compress7z combo needed to go - I had to add
a couple more parameters in compress7z - exe7z further encapsulated -
tmp helpers to add quotes in windows.

This was triggered by "7z" not being recognized in mac so:

bain.py 1386 _refreshSource: Unable to read archive '/Volumes/Samsung_T5/GAMES/Skyrim Special Edition Mods/Bash Installers/Unofficial Skyrim Special Edition Patch-266-4-1-2.7z'.
Traceback (most recent call last):
  File "/Users/ubik-mac13/Dropbox (Personal)/eclipse_workspaces/python/wrye-bash/Mopy/bash/bosh/bain.py", line 1382, in _refreshSource
    list_archive(tempArch, _parse_archive_line)
  File "/Users/ubik-mac13/Dropbox (Personal)/eclipse_workspaces/python/wrye-bash/Mopy/bash/archives.py", line 160, in list_archive
    proc = popen_common(command, encoding='utf-8')
  File "/Users/ubik-mac13/Dropbox (Personal)/eclipse_workspaces/python/wrye-bash/Mopy/bash/bolt.py", line 978, in popen_common
    return subprocess.Popen(popen_cmd, stdin=subprocess.DEVNULL,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '"7z" l -slt -sccUTF-8 "/Volumes/Samsung_T5/GAMES/Skyrim Special Edition Mods/Bash Installers/Unofficial Skyrim Special Edition Patch-266-4-1-2.7z"'

but as 7z cli is notorious this needs some testing. Centralizing is a step
towards # 562 RRR

I tried a couple mac 7z clients

See:
https://github.com/aonez/Keka/issues/799#issuecomment-783311150
for running 7z on  mac - create a bash alias as in

alias 7z='/Applications/Keka.app/Contents/MacOS/Keka --client 7z'

Edit: this needs shell=True in Popen - a no-no. So (given that for
instance on mac the command I used had two parts) I had to make
exe7z into a list - this is ungainly so yet another reson to encapsulate
it (and the commands) inside archives.py

My ini as an example:

[Settings]
;sCommand7z=/Applications/Keka.app/Contents/MacOS/Keka --client 7z
sCommand7z=/Users/me/Downloads/7z2107-mac/7zz

Managed to unzip on mac yey!

Note the

@@ -154,6 +155,6 @@ def compressionSettings(fn_archive, blockSize, isSolid):
 def _extract_command(archivePath, outDirPath, recursive, filelist_to_extract):
-    command = [exe7z, 'x', archivePath.s, '-y', '-bb1', '-o', outDirPath.s,
+    command = [exe7z, 'x', archivePath.s, '-y', '-bb1', f'-o{outDirPath}',
                '-scsUTF-8', '-sccUTF-8']
due to:

(popen_common(command, bufsize=1, encoding='utf-8').stdout.read())

'

Command Line Error:
Too short switch:
-o
'

TODO: this was not caught by regErrMatch and maybe we should do the regex
matching iff we get an error code to begin with

In my original version:

---------------------------- Mopy/bash/archives.py ----------------------------
index 6a86af6e2..5346ae7a7 100644
@@ -115,2 +115,3 @@ def wrapPopenOut(command, wrapper, errorMsg):
     # No encoding, this is *supposed* to return bytes!
+    command = shlex.split(command)
     proc = popen_common(command, bufsize=-1)
@@ -156,4 +157,5 @@ def _extract_command(archivePath, outDirPath, recursive, filelist_to_extract):
               f'-scsUTF-8 -sccUTF-8'
-    if recursive: command += u' -r'
-    if filelist_to_extract: command += f' @"{filelist_to_extract}"'
+    command  = shlex.split(command)
+    if recursive: command.append('-r')
+    if filelist_to_extract: command.append(f'@{filelist_to_extract}')
     return command

I use shlex to split - maybe we should write the command for the operating
system in str form then use shlex to split to a list?

squash!     Inline compressCommand: RRR TTT EEE add to default ini

Inlined also _extract_command - flat is better than nested. Note more
double quotes dropped

I included a commit by Infernio that however had a couple issues (most
notably having the -o as a separate item in the list) - here is the
commit message:

archives: Improve Linux support RRR TTT

Pass lists instead of strings to subprocess. That avoids needing to
quote paths, which fails when trying to use the 7z system executable on
Linux (we should probably use shutil.which to locate its full path as
well and pass that along).

Still doesn't get BAIN to the point where it can extract or install
archives on Linux (Ut: it now probably does), but it *can* now read
their contents.

Under # 243 <--- RRR

TTT on Windows, currently on Linux