610 WIP
test_setlocale_sv_SE RRR

Let's see if this fails - see:
https://github.com/wrye-bash/wrye-bash/issues/ <--- RRR 610#issuecomment-997463981

Does not prevent the locale crash - still maybe needed to move higher
(before ArtProvider)

Test for docbrowser image crash FAILS!!

...
______________________ TestLocalize.test_setlocale_sv_SE ______________________

self = <bash.tests.test_localize.TestLocalize object at 0x000002D1201EB0D0>
capsys = <_pytest.capture.CaptureFixture object at 0x000002D1201EB160>

    def test_setlocale_sv_SE(self, capsys):
        """Test setting locale to sv_SE - latest failure."""
>       self._test_locale('sv_SE', capsys)

Mopy\bash\tests\test_localize.py:82:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <bash.tests.test_localize.TestLocalize object at 0x000002D1201EB0D0>
loc = 'sv_SE'
capsys = <_pytest.capture.CaptureFixture object at 0x000002D1201EB160>

    def _test_locale(self, loc, capsys):
        with capsys.disabled():
            print(f'\n\n******* Testing {loc=} *******')
            wx_locale = setup_locale(loc, _wx)
            # getlocale = locale.getlocale()
            # print(getlocale)
            # assert getlocale
            # call the wx API that blows
            assert _wx.ArtProvider.GetBitmap(_wx.ART_PLUS, size=(16, 16))
>           assert _wx.Bitmap(_pj(_img_folder, 'reload16.png'),
                              _wx.BITMAP_TYPE_PNG)
E           wx._core.wxAssertionError: C++ assertion "wxString::Format("%.3f", 1.23).find(str) != wxString::npos" failed at ..\..\src\common\intl.cpp(1633) in `anonymous-namespace'::GetInfoFromLCID(): Decimal separator mismatch -- did you use setlocale()?If so, use wxLocale to change the locale instead.

Mopy\bash\tests\test_localize.py:58: wxAssertionError
=========================== short test summary info ===========================
FAILED Mopy/bash/tests/test_localize.py::TestLocalize::test_setlocale_pl_PL
FAILED Mopy/bash/tests/test_localize.py::TestLocalize::test_setlocale_de_DE
FAILED Mopy/bash/tests/test_localize.py::TestLocalize::test_setlocale_sv_SE
======================= 3 failed, 132 passed in 10.33s ========================
Error: Process completed with exit code 1.

Don't set LC_NUMERIC to C - still fails only for sv_SE !

            assert _wx.ArtProvider.GetBitmap(_wx.ART_PLUS, size=(16, 16))
>           assert _wx.Bitmap(_pj(_img_folder, 'reload16.png'),
                              _wx.BITMAP_TYPE_PNG)
E           wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
E           Things are going to break, please only change locale by creating wxLocale objects to avoid this!

Mopy\bash\tests\test_localize.py:58: wxAssertionError
=========================== short test summary info ===========================
FAILED Mopy/bash/tests/test_localize.py::TestLocalize::test_setlocale_sv_SE
======================= 1 failed, 134 passed in 10.33s ========================
Error: Process completed with exit code 1.

Note:

E                   AttributeError: module 'locale' has no attribute 'LC_MESSAGES'

WIP trying to call wx.Locale once TTT

WIP rework init locale - this passes the tests for sv_SE also

FFFstrings

XXX locale tests print locale/default locale:

Mopy\bash\tests\test_localize.py

******* Testing loc='pl_PL' *******
getlocale: ('en_US', 'ISO8859-1')
getdefaultlocale: ('en_US', 'cp1252')
localize.py  146 setup_locale: Wrye Bash does not support the language family 'pl', will however try to set locale to 'pl_PL'
localize.py  158 setup_locale: Set wxPython locale to 'pl_PL'
******* Tested loc='pl_PL' *******
.

******* Testing loc='' *******
getlocale: ('en_US', 'ISO8859-1')
getdefaultlocale: ('en_US', 'cp1252')
localize.py  103 setup_locale: cli_lang='' - cli_target='' - falling back to (en_US, cp1252) from getdefaultlocale
localize.py  158 setup_locale: Set wxPython locale to 'en_US'
******* Tested loc='' *******
.

******* Testing loc='pl-PL' *******
getlocale: ('en_US', 'ISO8859-1')
getdefaultlocale: ('en_US', 'cp1252')
localize.py  103 setup_locale: cli_lang='pl-PL' - cli_target=None - falling back to (en_US, cp1252) from getdefaultlocale
localize.py  158 setup_locale: Set wxPython locale to 'en_US'
******* Tested loc='pl-PL' *******
.

******* Testing loc='de_DE' *******
getlocale: ('en_US', 'ISO8859-1')
getdefaultlocale: ('en_US', 'cp1252')
localize.py  131 setup_locale: Found translation file for language 'de_DE'
localize.py  158 setup_locale: Set wxPython locale to 'de_DE'
******* Tested loc='de_DE' *******
.

******* Testing loc='sv_SE' *******
getlocale: ('en_US', 'ISO8859-1')
getdefaultlocale: ('en_US', 'cp1252')
localize.py  146 setup_locale: Wrye Bash does not support the language family 'sv', will however try to set locale to 'sv_SE'
localize.py  158 setup_locale: Set wxPython locale to 'sv_SE'
******* Tested loc='sv_SE' *******

Add fr_CM test

for
https://discord.com/channels/537706885965676554/537710082755133460/924788631850319882
- passes :(

******* Testing loc='pl_PL' *******
getlocale: ('en_US', 'ISO8859-1')
getdefaultlocale: ('en_US', 'cp1252')
localize.py  146 setup_locale: Wrye Bash does not support the language family 'pl', will however try to set locale to 'pl_PL'
localize.py  158 setup_locale: Set wxPython locale to 'pl_PL'
******* Tested loc='pl_PL' *******
.

******* Testing loc='' *******
getlocale: ('en_US', 'ISO8859-1')
getdefaultlocale: ('en_US', 'cp1252')
localize.py  103 setup_locale: cli_lang='' - cli_target='' - falling back to (en_US, cp1252) from getdefaultlocale
localize.py  158 setup_locale: Set wxPython locale to 'en_US'
******* Tested loc='' *******
.

******* Testing loc='pl-PL' *******
getlocale: ('en_US', 'ISO8859-1')
getdefaultlocale: ('en_US', 'cp1252')
localize.py  103 setup_locale: cli_lang='pl-PL' - cli_target=None - falling back to (en_US, cp1252) from getdefaultlocale
localize.py  158 setup_locale: Set wxPython locale to 'en_US'
******* Tested loc='pl-PL' *******
.

******* Testing loc='de_DE' *******
getlocale: ('en_US', 'ISO8859-1')
getdefaultlocale: ('en_US', 'cp1252')
localize.py  131 setup_locale: Found translation file for language 'de_DE'
localize.py  158 setup_locale: Set wxPython locale to 'de_DE'
******* Tested loc='de_DE' *******
.

******* Testing loc='sv_SE' *******
getlocale: ('en_US', 'ISO8859-1')
getdefaultlocale: ('en_US', 'cp1252')
localize.py  146 setup_locale: Wrye Bash does not support the language family 'sv', will however try to set locale to 'sv_SE'
localize.py  158 setup_locale: Set wxPython locale to 'sv_SE'
******* Tested loc='sv_SE' *******
.

******* Testing loc='fr_CM' *******
getlocale: ('en_US', 'ISO8859-1')
getdefaultlocale: ('en_US', 'cp1252')
localize.py  103 setup_locale: cli_lang='fr_CM' - cli_target=None - falling back to (en_US, cp1252) from getdefaultlocale
localize.py  158 setup_locale: Set wxPython locale to 'en_US'
******* Tested loc='fr_CM' *******
.

Restore the InitLocale but only restore LC_TYPE to C locale

See:
https://bugs.python.org/issue38805#msg373896

Note now getlocale is returning None, None

Mopy\bash\tests\test_localize.py

******* Testing loc='pl_PL' *******
getlocale: (None, None)
getdefaultlocale: ('en_US', 'cp1252')
localize.py  146 setup_locale: Wrye Bash does not support the language family 'pl', will however try to set locale to 'pl_PL'
localize.py  158 setup_locale: Set wxPython locale to 'pl_PL'
******* Tested loc='pl_PL' *******
.

******* Testing loc='' *******
getlocale: (None, None)
getdefaultlocale: ('en_US', 'cp1252')
localize.py  103 setup_locale: cli_lang='' - cli_target='' - falling back to (en_US, cp1252) from getdefaultlocale
localize.py  158 setup_locale: Set wxPython locale to 'en_US'
******* Tested loc='' *******
.

******* Testing loc='pl-PL' *******
getlocale: (None, None)
getdefaultlocale: ('en_US', 'cp1252')
localize.py  103 setup_locale: cli_lang='pl-PL' - cli_target=None - falling back to (en_US, cp1252) from getdefaultlocale
localize.py  158 setup_locale: Set wxPython locale to 'en_US'
******* Tested loc='pl-PL' *******
.

******* Testing loc='de_DE' *******
getlocale: (None, None)
getdefaultlocale: ('en_US', 'cp1252')
localize.py  131 setup_locale: Found translation file for language 'de_DE'
localize.py  158 setup_locale: Set wxPython locale to 'de_DE'
******* Tested loc='de_DE' *******
.

******* Testing loc='sv_SE' *******
getlocale: (None, None)
getdefaultlocale: ('en_US', 'cp1252')
localize.py  146 setup_locale: Wrye Bash does not support the language family 'sv', will however try to set locale to 'sv_SE'
localize.py  158 setup_locale: Set wxPython locale to 'sv_SE'
******* Tested loc='sv_SE' *******