Monkey patch for Build Patch blowing on non path items:
https://discord.com/channels/537706885965676554/537710082755133460/931602708903911475
Traceback (most recent call last):
  File "C:\Games\Steam\steamapps\common\Fallout 4\Mopy\bash\balt.py", line 1756, in __Execute
    self.Execute()
  File "C:\Games\Steam\steamapps\common\Fallout 4\Mopy\bash\balt.py", line 809, in _conversation_wrapper
    return func(*args, **kwargs)
  File "C:\Games\Steam\steamapps\common\Fallout 4\Mopy\bash\basher\mod_links.py", line 959, in Execute
    if not self._Execute(): return # prevent settings save
  File "C:\Games\Steam\steamapps\common\Fallout 4\Mopy\bash\basher\mod_links.py", line 1030, in _Execute
    with PatchDialog(self.window, self._selected_info,
  File "C:\Games\Steam\steamapps\common\Fallout 4\Mopy\bash\basher\patcher_dialog.py", line 67, in __init__
    patcher.getConfig(patchConfigs) #--Will set patcher.isEnabled
  File "C:\Games\Steam\steamapps\common\Fallout 4\Mopy\bash\basher\gui_patchers.py", line 838, in getConfig
    config = super(_ListsMergerPanel, self).getConfig(configs)
  File "C:\Games\Steam\steamapps\common\Fallout 4\Mopy\bash\basher\gui_patchers.py", line 426, in getConfig
    self.configItems = [srcPath.s for srcPath in self.configItems if (
  File "C:\Games\Steam\steamapps\common\Fallout 4\Mopy\bash\basher\gui_patchers.py", line 426, in <listcomp>
    self.configItems = [srcPath.s for srcPath in self.configItems if (
AttributeError: 'str' object has no attribute 's'

Not sure why this broke but wait for 543 for a proper fix